### ISSUE TITLE
missing file?

### ISSUE THREAD

**Issue by jonorthwash** [langsci/latex-skeletons#3]
I'm having trouble using the `langscibook` class.  When I compile (even just the example in `paper/`, using `make`, after linking in the other relevant files), I get the following message:

```
! LaTeX Error: File `langsci-series.def' not found.
```

Is this file missing, or do I need it from somewhere else?

**Comment by Glottotopia** [comment]
Current TexLive installations should have that file in your tex tree. Otherwise, you can get one here: https://github.com/langsci/langscibook/blob/master/langsci-series.def . Put this file in your working directory.

**Comment by jonorthwash** [comment]
Aha, I needed to install the `texlive-publishers` package from my package manager.

Now I'm getting the following instead:
```
! LaTeX Error: File `scrpage2.sty' not found.
```

It appears that [this package is now obsolete](https://tex.stackexchange.com/a/541772/90570).  But it's also possible it's in a texlive package I don't have installed?

**Comment by jonorthwash** [comment]
> But it's also possible it's in a texlive package I don't have installed?

Nope, it appears to have been removed (from the `texlive-latex-recommended` package in Debian, at least) some time between the 2018 and the 2020 releases of TeX Live.  So this is a broken dependency for me, using the most recent version of TeX Live.

**Comment by kopeckyf** [comment]
Dear Jonathan,

could you please make sure that you have an up to date version of the skeleton? Following the discontinuation of `scrpage2` we updated the skeletons on 1 July. The current versions do not load `scrpage2`. 

If the problem persists, please contact us at support@langsci-press.org.

**Comment by jonorthwash** [comment]
I'm getting the problem with `langscibook` provided by Debian's latest TeX Live (2020.20200804).  Perhaps it doesn't have these updates yet.  Could you point out the commit where this was fixed?

**Comment by kopeckyf** [comment]
Ah, I thought you were referring to the distributed skeletons. The skeletons are stored in this repository and can be downloaded from our [Templates and tools web page](https://langsci-press.org/templatesAndTools). I would recommend using these skeletons.

The current version of `langscibook` on CTAN loads `scrpage2`. You should be able to install `scrpage2` on TeX Live 2020 by installing the `koma-script-obsolete` package. If that doesn't work, you can still obtain a copy of `scrpage2` [from CTAN directly](https://ctan.org/pkg/scrpage2) and store that in your current working directory. If you are an experienced LaTeX user, you could also have a look at the current version of `langscibook` at [langsci/langscibook](https://github.com/langsci/langscibook). The skeletons stored in this repository and linked on the web page are those we offer to end users, however.

**Comment by jonorthwash** [comment]
Understood; thanks, @kopeckyf.  I installed `koma-script-obsolete` from CTAN directly, since it does not appear to be available in Debian.  I may switch over to the skeleton directly (I didn't know there were sanctioned downloads!  I was trying to use it directly from GitHub).
