### ISSUE TITLE
Missing file `langsci_spinelogo_nocolor`

### ISSUE THREAD

**Issue by laszabine** [langsci/latex-skeletons#4]
There seems to be a file named `langsci_spinelogo_nocolor` missing from this repository. 

Steps to reproduce: 
```
git clone https://github.com/langsci/latex-skeletons.git
cd latex-skeletons/editedskeleton
make pdf
```

Error thrown: 
```! LaTeX Error: File `langsci_spinelogo_nocolor' not found.```

I'm on Fedora 33 using `texlive` and the package [`texlive-langsci-9:svn54393-33.fc33.noarch`](https://rpmfind.net/linux/RPM/fedora/updates/33/x86_64/Packages/t/texlive-langsci-svn54393-33.fc33.noarch.html) -- in case the file should be provided there but isn't.

**Comment by laszabine** [comment]
Workaround: download the file [from here](https://github.com/langsci/101/blob/master/langsci/graphics/langsci_spinelogo_nocolor.pdf) into the folder `editedskeleton`.

**Comment by Glottotopia** [comment]
Thanks for letting us know. The file should be available in the repositories now

**Comment by laszabine** [comment]
Thank you! :)
